using System;
using System.Collections.Generic;

namespace BulkPimRoleSettings.Models;

/// <summary>
/// Official Entra ID built-in roles from Microsoft Learn documentation.
/// https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/permissions-reference#all-roles
/// </summary>
public static class KnownEntraRoles
{
    /// <summary>
    /// Set of known role display names from the official "All roles" list.
    /// Used to filter out any non-standard or deprecated roles.
    /// </summary>
    public static readonly HashSet<string> DisplayNames = new(StringComparer.OrdinalIgnoreCase)
    {
        "Agent ID Administrator",
        "Agent ID Developer",
        "Agent Registry Administrator",
        "AI Administrator",
        "AI Reader",
        "Application Administrator",
        "Application Developer",
        "Attack Payload Author",
        "Attack Simulation Administrator",
        "Attribute Assignment Administrator",
        "Attribute Assignment Reader",
        "Attribute Definition Administrator",
        "Attribute Definition Reader",
        "Attribute Log Administrator",
        "Attribute Log Reader",
        "Attribute Provisioning Administrator",
        "Attribute Provisioning Reader",
        "Authentication Administrator",
        "Authentication Extensibility Administrator",
        "Authentication Extensibility Password Administrator",
        "Authentication Policy Administrator",
        "Azure DevOps Administrator",
        "Azure Information Protection Administrator",
        "B2C IEF Keyset Administrator",
        "B2C IEF Policy Administrator",
        "Billing Administrator",
        "Cloud App Security Administrator",
        "Cloud Application Administrator",
        "Cloud Device Administrator",
        "Compliance Administrator",
        "Compliance Data Administrator",
        "Conditional Access Administrator",
        "Customer Delegated Admin Relationship Administrator",
        "Customer Lockbox Access Approver",
        "Desktop Analytics Administrator",
        "Directory Readers",
        "Directory Synchronization Accounts",
        "Directory Writers",
        "Domain Name Administrator",
        "Dragon Administrator",
        "Dynamics 365 Administrator",
        "Dynamics 365 Business Central Administrator",
        "Edge Administrator",
        "Entra Backup Administrator",
        "Entra Backup Reader",
        "Exchange Administrator",
        "Exchange Backup Administrator",
        "Exchange Recipient Administrator",
        "Extended Directory User Administrator",
        "External ID User Flow Administrator",
        "External ID User Flow Attribute Administrator",
        "External Identity Provider Administrator",
        "Fabric Administrator",
        "Global Administrator",
        "Global Reader",
        "Global Secure Access Administrator",
        "Global Secure Access Log Reader",
        "Groups Administrator",
        "Guest Inviter",
        "Helpdesk Administrator",
        "Hybrid Identity Administrator",
        "Identity Governance Administrator",
        "Insights Administrator",
        "Insights Analyst",
        "Insights Business Leader",
        "Intune Administrator",
        "IoT Device Administrator",
        "Kaizala Administrator",
        "Knowledge Administrator",
        "Knowledge Manager",
        "License Administrator",
        "Lifecycle Workflows Administrator",
        "Message Center Privacy Reader",
        "Message Center Reader",
        "Microsoft 365 Backup Administrator",
        "Microsoft 365 Migration Administrator",
        "Microsoft Entra Joined Device Local Administrator",
        "Microsoft Graph Data Connect Administrator",
        "Microsoft Hardware Warranty Administrator",
        "Microsoft Hardware Warranty Specialist",
        "Network Administrator",
        "Office Apps Administrator",
        "Organizational Branding Administrator",
        "Organizational Data Source Administrator",
        "Organizational Messages Approver",
        "Organizational Messages Writer",
        "Partner Tier1 Support",
        "Partner Tier2 Support",
        "Password Administrator",
        "People Administrator",
        "Permissions Management Administrator",
        "Places Administrator",
        "Power Platform Administrator",
        "Printer Administrator",
        "Printer Technician",
        "Privileged Authentication Administrator",
        "Privileged Role Administrator",
        "Purview Workload Content Administrator",
        "Purview Workload Content Reader",
        "Purview Workload Content Writer",
        "Reports Reader",
        "Search Administrator",
        "Search Editor",
        "Security Administrator",
        "Security Operator",
        "Security Reader",
        "Service Support Administrator",
        "SharePoint Administrator",
        "SharePoint Advanced Management Administrator",
        "SharePoint Backup Administrator",
        "SharePoint Embedded Administrator",
        "Skype for Business Administrator",
        "Teams Administrator",
        "Teams Communications Administrator",
        "Teams Communications Support Engineer",
        "Teams Communications Support Specialist",
        "Teams Devices Administrator",
        "Teams External Collaboration Administrator",
        "Teams Reader",
        "Teams Telephony Administrator",
        "Tenant Creator",
        "Tenant Governance Administrator",
        "Tenant Governance Reader",
        "Tenant Governance Relationship Administrator",
        "Tenant Governance Relationship Reader",
        "Usage Summary Reports Reader",
        "User Administrator",
        "User Experience Success Manager",
        "Virtual Visits Administrator",
        "Viva Glint Tenant Administrator",
        "Viva Goals Administrator",
        "Viva Pulse Administrator",
        "Windows 365 Administrator",
        "Windows Update Deployment Administrator",
        "Yammer Administrator"
    };

    /// <summary>
    /// Returns true if the given role display name is a known official Entra ID role.
    /// </summary>
    public static bool IsKnownRole(string roleDisplayName)
        => DisplayNames.Contains(roleDisplayName);
}
